name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Python tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"] # Empty string will trigger a build with the latest python version
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Install Hatch
        run: |
          pip install hatch
      - name: Build Ypy
        run: |
          unset CONDA_PREFIX 
          hatch run maturin develop
      - name: Run Tests
        run: |
          hatch run pytest
