name: Build fib-pyrs wheel
on: [push]

jobs:
  build-wasm-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          # Match Pyodide Python version which is 3.10.2 since 0.20.0
          # https://pyodide.org/en/stable/project/changelog.html#version-0-20-0
          python-version: '3.10.2'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            # maturin build will generate args -Z link-native-libraries=no which is only accepted on nightly compiler
            toolchain: nightly
            profile: minimal
            override: true
      
      - name: Rust version
        run: rustup -V

      - name: Rustup add wasm32 target
        # maturin build --target wasm32-unknown-emscripten requires rust to add that target first
        run: rustup target add wasm32-unknown-emscripten

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with: 
          # Match the emscripten version Pyodide builds with, which is 3.1.14 since 0.21.0
          # https://pyodide.org/en/stable/project/changelog.html#version-0-21-0
          version: 3.1.14 

      - name: Build WASM wheel
        uses: messense/maturin-action@v1
        with:
          target: wasm32-unknown-emscripten
          args: --release --out dist --find-interpreter 